### ISSUE TITLE
Use a configuration file to deploy to ReadTheDocs

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#18]
## Context

You are using ReadTheDocs web interface to configure the Sphinx project. However, you could lose the configuration if you change it over time. 

Instead, it's recommended to store a [configuration file for RTD](https://docs.readthedocs.io/en/stable/config-file/v2.html) within the repository.

## Proposal

1. Create a configuration file to deploy to RTD. For example:

```
# File: .readthedocs.yaml

version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: srsran_user_manuals/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  version: 3.7
  install:
    - requirements: requirements.txt
```

2. Remove the current configuration from the RTD panel and make sure the docs build without errors.
